tweetCreateForm.directive("tweetCreateForm",function(){
	return{
		templateUrl:"./js/components/tweetCreateForm/template.html",
		controller:"TweetCreateFormController",
		replace:true,
		scope:{
			socket:'='
		}
	}
})