angular.module("aTwitter",[
	"pages",
	"components",
	"services",
	"ngRoute",
	"ngResource",
	"ui.bootstrap",
	])
 .config(function($routeProvider){
 	$routeProvider
 		.when("/signIn",{
 			templateUrl:"./js/pages/signIn/index.html",
 			controller:"SignInController",
 			resolve:{
 				checkLogin:function($location){
 					if(localStorage.Identifier)
 						$location.path("/")
 				}
 			}
 		})
 		.when("/signUp",{
 			templateUrl:"./js/pages/signUp/index.html",
 			controller:"SignUpController",
 			resolve:{
 				checkLogin:function($location){
 					if(localStorage.Identifier)
 						$location.path("/")
 				}
 			}
 		})
 		.when("/",{
 			templateUrl:"./js/pages/home/index.html",
 			controller:"HomeController",
 			resolve:{
 				checkLogin:function($location){
 					if(!localStorage.Identifier)
 						$location.path("/signIn")
 				}
 			}
 		})
 		.when("/notifications",{
 			templateUrl:"./js/pages/notifications/index.html",
 			controller:"NotificationsController",
 			resolve:{
 				checkLogin:function($location){
 					if(!localStorage.Identifier)
 						$location.path("/signIn")
 				}
 			}
 		})
 		.when("/:userHandle",{
 			templateUrl:"./js/pages/profile/index.html",
 			controller:"ProfileController",
 			resolve:{
 				check:function($location,$routeParams){
 					console.log($routeParams);
 					if($routeParams.userHandle==localStorage.userHandle)
 						$location.path("/")
 				}
 			}
 		})
 })