header.directive("header",function(){
	return{
		templateUrl:"./js/components/header/template.html",
		controller:"HeaderController",
		replace:true,
		scope:{
			profile:'=',
			notifCount:'='
		}
	}
})